[build]
functions = "netlify/functions/"

[functions]
node_bundler = "esbuild"

[[edge_functions]]
path = "/qr-code"
function = "ab-test"

[[edge_functions]]
path = "/qr-code.html"
function = "ab-test"

# can't redirect the form submission or the function hook won't fire
# [[redirects]]
# from = "/submit"
# to = "/thank-you"
# status = 302
