[build]
functions = "netlify/functions/"

[functions]
node_bundler = "esbuild"

# can't redirect the form submission or the function hook won't fire
# [[redirects]]
# from = "/submit"
# to = "/thank-you"
# status = 302
